#common config which can run in the both environment
spring.datasource.url=jdbc:mysql://localhost:3306/employee
spring.datasource.username=root
spring.datasource.password=Password@0123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.owner=Mayur The Developer

#spring.profiles.active=dev,prod
server.port=9898



